### ISSUE TITLE
Deepspeech hotword engine for Google Assistant

### ISSUE THREAD

**Issue by TheSpaceGod** [BlackLight/platypush#138]
Hello,  I have been looking through this codebase for awhile and read through this article on medium (https://medium.com/better-programming/building-your-custom-voice-assistants-an-overview-of-the-current-solutions-and-integrations-d8db227a325), yet I can still not see how STT backends/plugins can connect to preferred assistants.  Is this functionality supported and I am just not seeing it?  Is it possible to have Mozilla Deepseech act as a (hotword/wake-word) engine for the Google Assistant SDK?  If it is possible, can you please link me to some sort of example on how to get these two components to communicate with each other?

Thanks!

**Comment by BlackLight** [comment]
I tried to build the hotword detection functionality into the Deepspeech integration back then. Although the [documentation still references](https://platypush.readthedocs.io/en/latest/platypush/plugins/stt.deepspeech.html#platypush.plugins.stt.deepspeech.SttDeepspeechPlugin.__init__) the support for the `hotword`/`hotwords` settings, those are actually no longer functional in the code. Two reasons:

- Deepspeech is (or at least it was, as of last time I tested it around 4 months ago) quite heavy even on a recent RaspberryPi 4. In spite of all the efforts to make the model as light as possible, it still takes 100% of a RPi4 core for speech detection when idle. The Google Assistant library in comparison takes around 8%. So I considered Deepspeech way too heavy to be used for hotword detection.

- Since it's not natively designed with hotword detection in mind, Deepspeech tries to extract meaningful speech even when you just say the hotword. That triggered, at least in my case, way more false positives and false negatives than another engine designed with hotword detection in mind (like the Google Assistant library, Snowboy or the PicoVoice suite).

So my suggestions would be:

- If you don't mind potentially losing a bit of privacy, use the Assistant library (keeping in mind however that it's officially deprecated by Google and it doesn't come on some devices/architectures).

- If you don't mind losing a bit of precision, Snowboy is a cheap and quick option, and the Platypush integration can be used to easily trigger a lot of custom assistants.

- If you don't mind paying some money for a license, get a PicoVoice Porcupine license for hotword detection and use the Platypush plugin.

- If you don't mind keeping at least one CPU core at 100% load and losing some accuracy on hotword detection, then you can leave this ticket open and I'll restore the code that triggers [`HotwordDetectedEvent`](https://platypush.readthedocs.io/en/latest/platypush/events/stt.html#platypush.message.event.stt.HotwordDetectedEvent) in Deepspeech.

**Comment by TheSpaceGod** [comment]
Thanks for the response and for summarizing the options for me!  Yeah, that makes sense.  I wanted to have an open source solution (besides the assistant) if it was possible that was also not being deprecated, but it seems like that just might not work out right now.  With the Google Assistant library being deprecated, Snowboy being set to have no further work done to it soon, and Deepspeech not really being set up for hotword detection; I think I will probably end up going with PicoVoice.
