### ISSUE TITLE
Continuing from Issue #157

### ISSUE THREAD

**Issue by billwatsonaz** [BlackLight/platypush#158]
Sorry it took me so long to reply to your last post. I moved the zwave information to the very end of the config.yaml file and started the application using "python3 -m Platypush", but when I got to http://localhost:8008/ I still get an error saying "The Site Cannot be Reached: localhost refused to connect."

I really do thank you for all of your help and look forward to getting this working soon!

Bill

**Comment by BlackLight** [comment]
It should be `python3 -m platypush` (lowercase p).

Can you post the new configuration and what you get on the logs? In theory all you need to enable the web server is this:

```yaml
backend.http:
  enabled: true
```

**Comment by billwatsonaz** [comment]
Hi Fabio - 

Here is my configuration and log file. Thanks again for your help.

Bill

[config.yaml.txt](https://github.com/BlackLight/platypush/files/5798818/config.yaml.txt)
[platypush.log](https://github.com/BlackLight/platypush/files/5798821/platypush.log)

**Comment by BlackLight** [comment]
If you look at your `config.yaml` you'll find something like this:

```yaml
backend.http.poll:
    requests:
        - some list of
        - RSS feeds

## --
## Procedure examples
## --
#
# some
# commented
# lines
        - action: light.hue.on
```

That basically means that the hanging `action: light.hue.on` is treated as part of the previous YAML block (`backend.http.poll`) - note that indentation matters in YAML.

Therefore, the interpreter tries to treat it as such, and it fails because it's obviously not a valid HTTP poll source.

Note that the example configuration file is meant to be a template on how to configure Platypush for your specific use-case. It's not something that you can blindly copy-paste, comment out a few lines and it works for your exact case.

Make sure that what belongs to each configuration block (backend or plugin) actually belongs to that block, otherwise you'll have errors because of invalid configuration. If there are too many commented lines don't be afraid of removing them, otherwise it's very hard to tell what belongs to what block. And also make sure to customize the configuration with the actual paths on your system - an SQLite engine like `sqlite:////home/user/.local/share/platypush/feeds/rss.db` probably won't go very far unless you change `user` to match your username, and `device_id: myname` is also just an example that should probably modified (or even just dropped, with no `device_id` specified the hostname will be used).

Also make sure to run your configuration through a [YAML validator](https://yamlvalidator.com/) to make sure that there aren't any hanging blocks or sections or syntax errors.

**Comment by billwatsonaz** [comment]
Thanks. I will try this and open a new ticket if I am still having issues.
