### ISSUE TITLE
zigbee.mqtt.device_get not working

### ISSUE THREAD

**Issue by ChrisDodgeRR** [BlackLight/platypush#163]
When using this action, I always get a timeout error returned from Platypush: 'timeout of 60000ms exceeded'.

Looking at the zigbee.mqtt plugin, I think the issue is that the mqtt publish call sends an empty message (lines 336 & 337):

```
properties = self.publish(topic=self._topic(device + '/get'),
                                  reply_topic=self._topic(device), msg='', **self._mqtt_args(**kwargs)).output
```

It works if I change it to:
```
properties = self.publish(topic=self._topic(device + '/get'),
                                  reply_topic=self._topic(device),
                                  msg={property: ""}, **self._mqtt_args(**kwargs)).output
```

The comments for this function also say that the property argument default is 'all', however this doesn't seem to work (i.e. timeout), unless that's an issue with zigbee2mqtt and Philips Hue lamps?

Thanks,

Chris

**Comment by BlackLight** [comment]
That's interesting, I haven't tested the `zigbee.mqtt` in about a year so it's likely that something has changed on the zigbee2mqtt side in the meantime.

I've [pushed a fix](https://github.com/BlackLight/platypush/commit/7ff08a9587f9478650c18a839a3ac38cea1a9eff) for it but I can't test it myself (I don't have some spare Hue bulbs or other Zigbee devices at hand right now).

Also, the empty message is used on several other Zigbee actions as well, do they work for you or is it just an issue with `device_get`?

**Comment by ChrisDodgeRR** [comment]
In the fix, the message property is now passed as a string, but I think it should be the property variable.

Testing the fix "as-is", if I request the brightness of a lamp, the MQTT message sent by Platypush is:

`{"property": ""}`

and I get no response from zigbee2mqtt.

If instead that line of code in `device_get` is `msg={property: ''}`, then the MQTT message and response is:

```
{"brightness": ""}
{"brightness":254,"color_temp":366,"linkquality":52,"state":"OFF"}
```
(What zigee2mqtt returns is slightly inconsistent as it will return the requested value, but will sometimes include additional values as in the example above. I notice that Playtpush filters the list and returns only the requested value, which seems perfectly sensible.)

I'm afraid that I don't have any other Zigbee devices at the moment apart from Philips Hue lamps and switches. However I think that passing the property variable is correct as this is what the zigbee2mqtt docs say:

> **zigbee2mqtt/[FRIENDLY_NAME]/get #**
> This is the counterpart of the set command. It allows you to read a value from a device. To read e.g. the state of a device send the payload {"state": ""}. What you can /get is specified on the device page under the “Exposes” section.

So this fix generates MQTT messages according to the zigbee2mqtt docs. If the previous behaviour is required, i.e. no property value given in the hope that zigbee2mqtt will return all properties in some future version, then it can be left empty in the call to `device_get`.

Currently, when this is done, the zigbee2mqtt logs say:

```
{"level":"debug","message":"Received MQTT message on 'zigbee2mqtt/TestLamp/get' with data '{\"\": \"\"}'"}
{"level":"error","message":"No converter available for '' ()"}
```

I've just updated to zigbee2mqtt V1.17.0 and it has the same behaviour.

**Comment by BlackLight** [comment]
After taking another look at the zigbee2mqtt specifications I should have managed to [push a proper fix](https://github.com/BlackLight/platypush/commit/31b110a06c3f6d80db90956a29b8d524a42c093a).

I'm pretty sure that in previous versions of zigbee2mqtt it was possible to call the `/<device>/get` endpoint with an empty message to get all the properties (or at least that worked when I tested it), but now it seems that zigbee2mqtt makes a clear distinction between `/<device>` (get all the device properties) and `/<device>/get` (get only one device property). I understand the argument for having a `/get` that mirrors 1-1 the behaviour of `/set`, but this is definitely confusing because we are supposed to use two different topics depending on whether we want to get all the device properties or only one - plus we're passing a dictionary with empty values over `/get`...

As before, this is more or less a "blind fix" based on the documentation, since it'd take me a while to get a Zigbee device and an adapter to test, so let me know if it works in your case.

Also, I've noticed that the documentation of `device_get` is a bit misleading - when it says _(default: all)_ it actually means "by default get all the properties", but the default is actually an empty string :)

**Comment by ChrisDodgeRR** [comment]
Thanks for the fix - that works well now.

I think the zigbee2mqtt docs are misleading with the `/<device>` topic as I can't get that to work at all; it just seems to be ignored by zigbee2mqtt.

Fortunately the Platypush web UI now returns immediately (i.e. no timeout) if the property field is empty, but with an empty result rather than all properties. This is at least consistent - empty property gives an empty result - but doesn't follow the `device_get` docs.

I'll try and follow this up with zigbee2mqtt...

**Comment by ChrisDodgeRR** [comment]
OK - I think I understand now. The topic `zigbee2mqtt/FRIENDLY_NAME` is used by zigbee2mqtt to publish data whenever any of the exposed properties change.

It can be subscribed to but publishing to it does nothing as far as I can tell.

**Comment by BlackLight** [comment]
It'd be interesting then to know what topic I'm supposed to subscribe to get the full list of attributes of a Zigbee device, the Platypush plugin is supposed to be as agnostic as possible about the type of device used.

I recall that `/get` with an empty message used to work when I developed the plugin about a year ago, but if that's no longer the case then it'd be great to have an alternative - I'll test it again over the next days with another Zigbee device, in the meantime feel free to reach out to the zigbee2mqtt guys for more clarity and link the issue here so I can keep track of it.
